### ISSUE TITLE
Difference between dashboard roles

### ISSUE THREAD

**Issue by pim-simons** [invictus-integration/docs-ifa#119]
From the documentation it is not clear what the difference between the Folder Admin and Operator roles are. 
See:
https://invictus-integration.github.io/docs-ifa/#/dashboard/role-management?id=folder-admin
https://invictus-integration.github.io/docs-ifa/#/dashboard/role-management?id=operator

Folder admin states: _this role can perform certain administrative tasks only within the folder where he/she is assigned to, and cannot manage users on the dashboard in general._ 
Operator states:  _Users with this role can perform certain tasks within the folder and its flows._

What are these "certain tasks" per role. To me it is not immediately clear when to choose which role.

**Comment by gregphillipson** [comment]
+1

**Comment by adrideba** [comment]
These are the differences:

![image](https://user-images.githubusercontent.com/4602977/203715375-152ed50a-4db5-48a6-b412-51f1353bd401.png)

**Comment by pim-simons** [comment]
Dont know how I missed that table, thanks!
