### ISSUE TITLE
Describe the dashboard configuration json used to configure flows through release pipelines

### ISSUE THREAD

**Issue by ccstorm-nl** [invictus-integration/docs-ifa#129]
Unless I am missing something, this requires some attention. Especially setting authentication against pre-configured AAD roles needs both explanation and examples.

**Comment by pim-simons** [comment]
Possible what you are looking for can be found [here](https://github.com/Codit/integration-practice/blob/main/src/invictus/Dashboard-Configuration.md)
If those docs are not clear enough or need more samples feel free to create an issue for that or even better create a PR 😉 

But the fact that you could not find the right docs means something as well. Maybe we should add a link to [these docs](https://github.com/Codit/integration-practice/blob/main/src/invictus/Dashboard-Configuration.md) from this repo though 🤔

**Comment by ccstorm-nl** [comment]
> Possible what you are looking for can be found [here](https://github.com/Codit/integration-practice/blob/main/src/invictus/Dashboard-Configuration.md) 

If we document Invictus functionality outside of this repo then I think we need to put it here and link back from Coldit practices. This allows a separation of internal and external practices from out to in, not vv.

**Comment by GoutsmitSam** [comment]
Since the pipelines have in the meantime changed because of the V2, let's close this issue for now.
