### ISSUE TITLE
Variable groups must be linked to the release pipeline

### ISSUE THREAD

**Issue by jdefesche1** [invictus-integration/docs-ifa#137]
@pim-simons  There is no entry in the documentation that the Invictus and Infra resourcegroups should be linked to the yaml release pipeline

**Comment by pim-simons** [comment]
Not sure what you mean? Do you have an example?

**Comment by jdefesche1** [comment]
If I run my release pipeline it complains the $(Infra.Environment.ServiceConnection) does not exist or that there is no authorization. It tells me that the replacement with actual values doesn't take place. If I go my release yml pipeline and link the variable groups, then it works. So to me (not a yml guru), this should be added to the documentation.

**Comment by pim-simons** [comment]
These are already defined in the templates:
https://github.com/invictus-integration/docs-ifa/blob/master/framework/installation/pipelines/framework.release.yaml#L38
https://github.com/invictus-integration/docs-ifa/blob/master/dashboard/installation/pipelines/dashboard.release.yaml#L38

That should be enough I think? Or do you think we need to specifically mention this in the docs?

**Comment by jdefesche1** [comment]
Yes they are there but I think in the template you link the correct variable group to the step, whereas in the UI you need to link the variable groups to the release pipeline itself.

This was the only way to get it to work. At Leenbakker we have yml pipelines for build & release (integrated in one pipeline) and there we don't have to do this linking of variable groups.

It may still be something that is specific for my scenario. If you don't encounter it, please ignore it then. Or help me on how to set it up :-)

**Comment by pim-simons** [comment]
I don't really understand what you mean by linking in the UI? That shouldnt be necessary if you use YAML pipelines, I have these exact YAML files in use at several customers, maybe we can schedule a meeting to see what is happening exactly. Let's discuss offline, if necessary we can reopen this issue 👍🏻
