### ISSUE TITLE
Folders appear double in dashboard

### ISSUE THREAD

**Issue by Anton90** [invictus-integration/docs-ifa#139]
Hi, 

At a customer we are using groups to grant access to the dashboard flows and that works. 
But I have noticed that when someone is part of a group that has access to a flow and also a dashboard system admin, then those flows are appearing two times for them.  
Is this normal behavior and is there a way to fix this? 

Thank you. 

Kind regards, 
Anton

**Comment by pim-simons** [comment]
@grik001 this is probably the same as one of the issues reported by @twinpiloot over email correct?

**Comment by grik001** [comment]
Fixed

**Comment by pim-simons** [comment]
@grik001 which release was this fixed in?

**Comment by grik001** [comment]
Hi Pim, in the last release.

**Comment by pim-simons** [comment]
> Hi Pim, in the last release.

Thanks! By the way, the [latest release](https://github.com/invictus-integration/docs-ifa/releases/tag/4.16.4) is still marked as preview, but from the info in the Teams channel it seems like it is already released.

**Comment by grik001** [comment]
Thanks Pim, updated release to latest. Yes everything is on production.
