### ISSUE TITLE
Installing Multipass (via Microk8s) not always able to activate Hyper-V

### ISSUE THREAD

**Issue by stijnmoreels** [invictus-integration/docs-ifa#149]
**Is your feature related to a problem? Please describe.**
When installing the hybrid Invictus framework components on Windows, the Microk8s may not be able to activate Hyper-V (not enough additional info on reason, may be because it is already active).

**Describe what solution you propose:**
Mention the possibility that activating Hyper-V through Microk8s installation may fail. Maybe there is a FAQ or Troubleshooting guide for Microk8s that explains more why it may fail to activate Hyper-V during installation.

**Comment by stijnmoreels** [comment]
Apparently, this is a known issue with installing Multipass.https://github.com/canonical/multipass/issues/1548

**Comment by LaurentAerens** [comment]
someone even made an small article on how to fix this issue https://medium.com/@antongslismith/multipass-with-hyper-v-on-windows-10-home-7fd783d83978
