### ISSUE TITLE
Deploying Helm chart missing information

### ISSUE THREAD

**Issue by stijnmoreels** [invictus-integration/docs-ifa#152]
**Is your feature related to a problem? Please describe.**
The hybrid Invictus framework installation guide only provides the Helm command to deploy a Helm chart but I'm guessing there is some missing information or there is some obscure assumptions being made.

**What solution do your propose?**
I'm guessing there needs to be an ARM/Bicep template deployed before we can run this Helm command? So you can place the necessary connection strings/names as arguments for the command parameters?
We should provide maybe more info on each argument, as right now, it only describes the name of the parameter, not the function, the reason why it is there, or where you should find it.

**Comment by stijnmoreels** [comment]
After some research, I'm also not very sure on how we do this deployment to Microk8s?
How does the helm command know it has to use the local Kubernetes cluster?
Providing a Kubernetes namespace would be my guess.

**Comment by stijnmoreels** [comment]
Also, I think that we only need to run:
```shell
> helm upgrade --install <name> oci://invictusdevacracr.azurecr.io/helm/invictus-on-premise
```

When getting the Kubernetes pods, you get these already:

![image](https://user-images.githubusercontent.com/9039753/215974548-cb031962-5008-4408-ab35-1486ca01c5bd.png)

**Comment by LaurentAerens** [comment]
I'm more of a fan to let the use --set with the command an not inject values in values.yaml.
For micok8s you can just do microk8s config > .kube/config an use it as a normal Kubernetes cluster.

**Comment by stijnmoreels** [comment]
Aha, didn't know that. Thx!

**Comment by LaurentAerens** [comment]
just clarified with Matthew. That Framework.InvictusDashboardConnectionString is an outdated variable and isn't needed anymore.
All other needed variables should be clear. right?

**Comment by stijnmoreels** [comment]
> just clarified with Matthew. That Framework.InvictusDashboardConnectionString is an outdated variable and isn't needed anymore. All other needed variables should be clear. right?

Some questions on these variables:

* `{name}`: this is something we can choose freely? Could be anything we want?
* `{username}`/`{password}`: 'credentials by Codit products'? So, credentials I still require?
* `{rabbitmqpassword}`: also an Azure resource I have to deploy manually?
* `{erlangcookie}`: something we can choose freely?
* `{releaseverion}`: an existing release version? If so, what are available? If not, can we choose it freely?

**Comment by stijnmoreels** [comment]
Currently trying to deploy with this information, but wondering if the `oci://invictusdevacracr.azurecr.io/helm/invictus-on-premise` is correct here, as I continuously receive  a `Not Found` failure on this (while I found it on Azure).

Is the `/helm/invictus-on-premise` part supposed to be an existing repository in the Azure ACR? Or should this be a new name?

**Comment by stijnmoreels** [comment]
Ok, I think I got the deploy commanded working; now I only need something to see if everything works.

**Comment by stijnmoreels** [comment]
First thought that the `mysql` pod was some built-in stuff, but apparently, this is part of the deploy. It is the only pod that's failing due to missing file permissions: `/opt/mssql/bin/sqlservr: Error: The system directory [/.system] could not be created. File: LinuxDirectory.cpp:420 [Status: 0xC0000022 Access Denied errno = 0xD(13) Permission denied]`; this is also via the `SQLsapassword` stuff, not the `SQLexistingconnectionstring` one.

**Comment by stijnmoreels** [comment]
> can you check if the rabbitmq is deployed successfully?

Has the `Running` status and the logs seem also OK. (started, completed).

**Comment by LaurentAerens** [comment]
let me check, all of this should be automated. but maybe There was a change that wans't applied everywhere.

**Comment by LaurentAerens** [comment]
about the timesequencer. somewhere that fix was removed from the repo. it think with the switch from github to devops.
I'll add it again.

**Comment by stijnmoreels** [comment]
> about the timesequencer. somewhere that fix was removed from the repo. it think with the switch from github to devops. I'll add it again. edit: a fix has been deployed try to remove the helm chart and reinstall it.

Something got wrong with the update? Some corrupt secret?
```
Release "release-name" does not exist. Installing it now.
Pulled: invictusdevacracr.azurecr.io/helm/invictus-on-premise:1.0.0
Digest: sha256:ddfad5eddb3ffc8001176f21251045e8ce4e037abb93d82f1f5a656bd6791f8a
Error: Secret in version "v1" cannot be handled as a Secret: illegal base64 data at input byte 12
```

**Comment by LaurentAerens** [comment]
indeed, fix that. I don't know why the test run didn't fail.

**Comment by stijnmoreels** [comment]
Additional info on the SQL error: https://github.com/microsoft/mssql-docker/issues/735.
Was thinking, since it is a Linux pod, that we should provide file permissions `chown` with the non-root user on the pod?

**Comment by LaurentAerens** [comment]
![image](https://user-images.githubusercontent.com/112876534/218411298-ecba1289-2c7d-4ca2-9538-125074611105.png)
i already set fsGroup to 10001
