### ISSUE TITLE
Prefer Managed Identity over Shared Access Keys for Storage Account

### ISSUE THREAD

**Issue by Pauwelz** [invictus-integration/docs-ifa#168]
Currently we're using Shared Access Keys for access to the Storage Account from all the applications needing it. All of these applications are running in Azure, so we should investigate the work to switching this over to Managed Identities. (This is coming from a customer that also requires Managed Identity instead of Shared Access Keys that can be "leaked")

**Comment by pim-simons** [comment]
Maybe we can look at using Managed Identities on a broader scope than just Storage Account? 
Should be possible to use this to call the API's also right?

**Comment by Pauwelz** [comment]
Perhaps, certainly if we use a User-Assigned one, we should be able to get all our Logic Apps to use the same one.
This was more from the customer perspective where they want it to be MI towards the Storage Account at first.

**Comment by pim-simons** [comment]
Indeed, add a user assigned managed identity to the Invictus for Azure deployment and use that to connect to all Invictus related components.

**Comment by stijnmoreels** [comment]
Thx, @Pauwelz , for all these security suggestions! There is indeed a great opportunity to improve this.
Thank you! 🏅

**Comment by GoutsmitSam** [comment]
@LaurentAerens @Pauwelz I suppose this issue can now also be closed?

**Comment by GoutsmitSam** [comment]
Issue can be closed as MSI changes have been added due to Ecofit requriements
