### ISSUE TITLE
Links to yaml pipelines do not work in docs

### ISSUE THREAD

**Issue by pim-simons** [invictus-integration/docs-ifa#174]
On the page https://invictus-integration.github.io/docs-ifa/#/dashboard/installation/dashboard-buildpipeline?id=yaml-pipeline we have a link to https://invictus-integration.github.io/docs-ifa/#/dashboard/installation/pipelines/dashboard.build.yaml, this however results in a 404. 

If I check the docs in the GitHub repo this does work: https://github.com/invictus-integration/docs-ifa/blob/master/dashboard/installation/dashboard-buildpipeline.md#yaml-pipeline points to https://github.com/invictus-integration/docs-ifa/blob/master/dashboard/installation/pipelines/dashboard.build.yaml which works. 

I don't really understand why this works in the GitHub repo but not on the website... 

Here are all the URL's that are used that do not work from the https://invictus-integration.github.io/docs-ifa page:
https://invictus-integration.github.io/docs-ifa/#/dashboard/installation/pipelines/dashboard.build.yaml
https://invictus-integration.github.io/docs-ifa/#/dashboard/installation/pipelines/dashboard.release.yaml
https://invictus-integration.github.io/docs-ifa/#/framework/installation/pipelines/framework.build.yaml
https://invictus-integration.github.io/docs-ifa/#/framework/installation/pipelines/framework.release.yaml

**Comment by stijnmoreels** [comment]
That's wrong indeed. Maybe it is something to with the type it references. It is not a page, but an actual file.
If we remove the `/#/` from the path, we still have the file, so it is hosted: https://invictus-integration.github.io/docs-ifa/dashboard/installation/pipelines/dashboard.build.yaml, only wrongly referenced.

Let's see. 👍

**Comment by stijnmoreels** [comment]
Used the GitHub file references instead for this one, as I imagine these will be changed for the new dashboard (and GitHub has a nicer way of formatting 😄).

Feel free to take a look at PR: https://github.com/invictus-integration/docs-ifa/pull/175
And deploy preview: https://deploy-preview-175--invictus-for-azure.netlify.app/#/ 
To see if everything is fixed now. 👍

Thx for noting!
