### ISSUE TITLE
Click on name to open folder

### ISSUE THREAD

**Issue by GoutsmitSam** [invictus-integration/docs-ifa#186]
[Anton for client Vervaeke]
Small improvement: Is it possible to be able to click on a folder name to open it as well as the dropdown arrow? Intuitively I always click on the name (as we do now in the current dashboard) and then have to change to click on the arrow. 
It would be logical if clicking on the name worked as well.

**Comment by GoutsmitSam** [comment]
This has been implemented and will be included in the next version of Invictus

**Comment by GoutsmitSam** [comment]
@pim-simons I realise my previous message might be a bit confusing, so for 100% clarity: the "Click on a name to open Folder" feature has been developed, not your hijack of the subject. 
Having said that, this issue (https://github.com/invictus-integration/docs-ifa/issues/193) should take care of your remark I think.

**Comment by pim-simons** [comment]
Sounds good, thanks for the clarification!
