### ISSUE TITLE
Add usage metrics, to give an idea how much/intensive a customer is using the dashboard

### ISSUE THREAD

**Issue by GoutsmitSam** [invictus-integration/docs-ifa#190]

**Comment by pim-simons** [comment]
Where will these metrics be available, in the customers Application Insights?

**Comment by GoutsmitSam** [comment]
@pim-simons No idea, information wasn't present in DevOps. @grik001 You have an idea of the context of this question?

**Comment by GoutsmitSam** [comment]
Discussed on the Steering Forum - this was meant as a metric to justify the V2 version, so obviously is no longer relevant
