### ISSUE TITLE
SequenceController missing from navigation sidebar

### ISSUE THREAD

**Issue by Annelotte-Mons** [invictus-integration/docs-ifa#202]
Sequence controller Framework component seems to be missing from the navigation sidebar:
https://invictus-integration.github.io/docs-ifa/#/framework/components/sequencecontroller

![image](https://github.com/invictus-integration/docs-ifa/assets/43070906/31a3ccd2-c8a2-4e23-b67a-c13e1f651058)

**Comment by GoutsmitSam** [comment]
Hi Annelotte, 
thanks for signaling this, the link to the SequenceController has been added to the sidebar.

KInd regards,

Sam
