### ISSUE TITLE
AI-enhanced Exception handler

### ISSUE THREAD

**Issue by GoutsmitSam** [invictus-integration/docs-ifa#232]
[Pim Simons]

At Van Gelder we use a common exception handler Logic App that is called by every other Logic App whenever something fails and within that common exception handler Logic App we call the Invictus for Azure exception handler component so we can log the actual error instead of An action failed. No dependent actions succeeded.
 
This is basically exactly the setup we documented here: https://github.com/invictus-integration/docs-ifa/blob/master/framework/components/exceptionHandler.md#guideline-on-how-to-implement-the-exception-handler 
 
This has already improved our exception handling and error logging quite a bit. However we found that quite regularly the errors being logged contained a lot of JSON that was part of the output of the failing Logic App action. This made it a bit hard to clearly identify the error, especially for people without technical knowledge.
 
So some weeks ago I set out to improve the error logging. Since the raw error can contain all kinds of data depending on the failing Logic App action I started playing around with AI and investigating if we could apply this here. 
Turns out, this works really really well 
 
With the help of Ruud Wichers Schreur we setup an Azure OpenAI instance with a chatgpt-4o model and added an extra step in my common exception handler Logic App to call the model. 
We use this call to ask the model to get the actual error from the supplied data:
 
{
    "messages": [{
            "role": "system",
            "content": "You are an AI assistant that helps interpret raw error messages. You will receive the raw error message, I want you to filter out the actual error. If the input is already a clear error than return the input."
        }, {
            "role": "user",
            "content": "{\"statusCode\":400,\"headers\":{\"Cache-Control\":\"no-store, no-cache\",\"Pragma\":\"no-cache\",\"Strict-Transport-Security\":\"max-age=31536000; includeSubDomains\",\"x-ms-request-id\":\"b7dfa47d-d205-4ffa-82ca-632c4832d679\",\"X-Content-Type-Options\":\"nosniff\",\"X-Frame-Options\":\"DENY\",\"x-ms-dlp-re\":\"-|-\",\"x-ms-dlp-gu\":\"-|-\",\"Timing-Allow-Origin\":\"*\",\"x-ms-apihub-cached-response\":\"false\",\"x-ms-apihub-obo\":\"false\",\"Date\":\"Tue, 10 Dec 2024 16:30:06 GMT\",\"Content-Length\":\"396\",\"Content-Type\":\"application/json\",\"Expires\":\"-1\"},\"body\":{\"status\":400,\"message\":\"Procedure or function 'upsertContactpersonen' expects parameter '@EmailAdres', which was not supplied.\\r\\nclientRequestId: b7dfa47d-d205-4ffa-82ca-632c4832d679\",\"error\":{\"message\":\"Procedure or function 'upsertContactpersonen' expects parameter '@EmailAdres', which was not supplied.\"},\"source\":\"sql-we.azconn-we-003.p.azurewebsites.net\"}}"
        }
    ],
    "max_tokens": 100
}
And we get back Procedure or function 'upsertContactpersonen' expects parameter '@EmailAdres', which was not supplied.
Which is exactly what we want 
 
So now our logging in the Invictus dashboard has improved from this:
to this:
 
We also sent out an email to several admins, which has improved from this:
to this:
 
A huge improvement that their admins are really happy with!! 
In all this took us only a couple of hours to setup, huge thanks to Ruud Wichers Schreur for helping me out on this 
 
This has been running for a couple of weeks now in production and so far we have not seen any weird behavior or raw errors being translated wrong. But we are keeping an eye out for the time being to see how it performs.
 
Running costs for the OpenAI instance so far has been €0.40 since the first of december with about 1800 calls done in that time to the model. So really cheap so far 
 
And since we are using a common exception handler Logic App I only had to modify this single Logic App and now all of our errors are being translated nicely. In all, an easy change with a big impact

**Comment by stijnmoreels** [comment]
Finished off in v6.3 without communication. Closing for now as development is done.
@pim-simons
