### ISSUE TITLE
Configure Netlify for documentation previews

### ISSUE THREAD

**Issue by tomkerkhove** [invictus-integration/docs-ifa#47]
Configure Netlify for documentation previews so that you can check the rendered version of the PR before merging.

This is what it looks like:
![image](https://user-images.githubusercontent.com/4345663/75423456-06caff00-593f-11ea-831e-2fe3347a75f7.png)

You can preview the docs but also blocks PRs where packaging fails.

## Configuration

You can easily configure this by:
1. Installing the Netlify GitHub app (https://github.com/apps/netlify)
2. Create a Netlify account
3. Add site for this GitHub repo

**Comment by SamVanhoutte** [comment]
Makes sense and does not look like a lot of work.  
@grik001 - could you plan this ?

**Comment by grik001** [comment]
@SamVanhoutte Sure will look into it.

**Comment by tomkerkhove** [comment]
Happy to help if you have questions!

**Comment by tomkerkhove** [comment]
It's configured under my account and an example is open on https://github.com/invictus-integration/docs-ifa/pull/56.

@SamVanhoutte we should check if we can buy a plan if you want to because I cannot invite anybody in free tier apparently. OSS tier is not an option given it's commercial product.

**Comment by tomkerkhove** [comment]
I think we can close this one

**Comment by SamVanhoutte** [comment]
close as in : "it's been done", or "will not do it" ?

**Comment by tomkerkhove** [comment]
Previews are done with sample in #56 but the plan is still pending but not blocking I think.
