### ISSUE TITLE
Publish docs on *.invictus-integration.com

### ISSUE THREAD

**Issue by tomkerkhove** [invictus-integration/docs-ifa#48]
Publish docs on `*.invictus-integration.com` to make it more consumer friendly, for example `azure.invictus-integration.com`.

This can be easily done with CloudFlare similar to Arcus (http://eventgrid.arcus-azure.net/, http://webapi.arcus-azure.net/, ...)

**Comment by tomkerkhove** [comment]
Would that be possible @SamVanhoutte?

**Comment by SamVanhoutte** [comment]
How much effort does this typically take?  Is there a lot of css-styling to be done?  
Will take it up with Sonia

**Comment by tomkerkhove** [comment]
It depends on how http://docs.invictus-integration.com/ is hosted but you could:
1. Move DNS name servers for invictus-integration.com to CloudFlare
2. Add CNAME for this doc (azure.invictus-integration.com -> https://invictus-integration.github.io/docs-ifa
2. Add CNAME for current docs on docs.invictus-integration.com

Would allow you to enforce & serve HTTPS withouth changing anything.

Example from Arcus:
![image](https://user-images.githubusercontent.com/4345663/75439275-c9279f80-5959-11ea-82be-744736c29c5e.png)

**Comment by tomkerkhove** [comment]
Any update on this @ssorianoc ?

**Comment by GoutsmitSam** [comment]
Closing this issue due to its old age.
